server:
   port: 8088 # 端口号
spring:
  application:
    name: news # 应用名称
#   MySQL 数据库驱动
#  datasource:
#    url: jdbc:mysql://localhost:3306/news_db?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver #  MySQL 数据库驱动
#    username: root # 数据库用户名
#    password: root # 数据库密码
#  DM 数据库驱动
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236/NEWS
    username: SYSDBA
    password: 122333zhanG
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis: #  Redis 配置
    database: 0 # Redis 数据库索引
    host: 127.0.0.1 # Redis 地址
    port: 6379 #  Redis 端口
    password: # Redis 密码
    timeout: 300 #  Redis 超时时间
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml # Mapper 文件位置
  type-aliases-package: com.news.com.news.domain.* # 实体类包名
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #  MyBatis 日志实现类